### ISSUE TITLE
Using baize.asgi.FileResponse instead of starlette.responses.FileResponse not working

### ISSUE THREAD

**Issue by AntonOvsyannikov** [abersheeran/baize#45]
Hello. I am trying to use baize.asgi.FileResponse instead of starlette.responses.FileResponse  as written in [doc](https://www.starlette.io/responses/) in FastAPI application.

With starlette.responses.FileResponse everyting works fine, at least wav file served correctly and response content-type is audio/wav

But if I replace it with baize.asgi.FileResponse the response content-type become application/json like this

```
{filepath":".....wav","content_type":"audio/wav","download_name":null,"stat_result":[33206,1407374884139494,583568122,1,0,0,35343404,1657731514,1657729813,1657729848],"chunk_size":262144}
```
So could you please explain how to use baize.asgi.FileResponse instead of  starlette.responses.FileResponse ?

Code snippet is below

```python
import logging
from pathlib import Path

from fastapi import APIRouter
# from starlette.responses import FileResponse
from baize.asgi import FileResponse

router = APIRouter(
    prefix='/audio',
    tags=['Audio'],
)


@router.get('/{path:path}')
def serve_audio(path: str):
    return FileResponse(
        str(Conf.LKB_AUDIODIR / path),
    )

```

**Comment by abersheeran** [comment]
Because fastapi will determine the return value type and try to convert it automatically, all objects that are not of type starlette.responses.Response will be automatically converted to JSON.

Maybe you can ask for help in fastapi community.

**Comment by xKlask** [comment]
I ran into this problem too. 
It's solvable without changing the code in FastAPI and help from the community. 

I'll show you some dirty ideas, what you can change to integrate seamlessly with FastAPI
P.S. I do not suggest Pull-request, as these are just ideas

Solved in a few steps by changing the file asgi/responses.py

1. Adding response_class like:
``` python
@router.get('/{path:path}', response_class=FileResponse)
def ...
```
2. Add bypass adding "background" param in FileResponse to prevent errors (in code bellow)
3. FastAPI Response sometimes sends the body of the request as the first argument, so as an idea, I suggest adding a dictionary check and rewriting the parameters manually. I think you can come up with a better solution
4. Repeated queries convert stat_result into a list, while we expect a different data type (result of os.stat), so it is easiest to delete the values and query again

``` python
class FileResponse(Response, FileResponseMixin):
    """
    File response.

    It will automatically determine whether to send only headers
    and the range of files that need to be sent.
    """

    def __init__(
        self,
        filepath: str,
        headers: Optional[Mapping[str, str]] = None,
        content_type: Optional[str] = None,
        download_name: Optional[str] = None,
        stat_result: Optional[os.stat_result] = None,
        chunk_size: int = 4096 * 64,
        background = None  # 2 - bypass
    ) -> None:
        super().__init__(headers=headers)
        # 3 - parsing if all data dumpt to first atrument
        if type(filepath) == dict:
            headers = filepath.get('headers', None)
            content_type = filepath.get('content_type', None)
            download_name = filepath.get('download_name', None)
            stat_result = filepath.get('stat_result', None)
            chunk_size = filepath.get('chunk_size', 4096 * 64)
            filepath = filepath.get('filepath')
        self.filepath = filepath
        self.content_type = (
            content_type
            or guess_type(download_name or os.path.basename(filepath))[0]
            or "application/octet-stream"
        )
        self.download_name = download_name
        # 4 - clear for queryng again 
        if type(stat_result) == list:
            stat_result = None
        self.stat_result = stat_result or os.stat(filepath)
        if stat.S_ISDIR(self.stat_result.st_mode):
            raise IsADirectoryError(f"{filepath} is a directory")
        self.chunk_size = chunk_size
        self.headers.update(
            self.generate_common_headers(
                self.filepath, self.content_type, self.download_name, self.stat_result
            )
        )
```

I hope this helps everyone who has a similar problem
Also hope for an update
Thank you so much for this repository!

**Comment by abersheeran** [comment]
Thanks for sharing.

> ```python
> from baize.asgi.responses import FileResponse
> from baize.datastructures import MutableHeaders
> 
> 
> def raw(self):
>     return []
> 
> 
> setattr(MutableHeaders, 'raw', property(raw))
> 
> 
> class ChunkFileResponse(FileResponse):
>     def __init__(self, *args, **kwargs) -> None:
>         if len(args) == 1:
>             kwargs = args[0]
>             [kwargs.pop(k) for k in ['status_code', 'cookies', 'stat_result']]
>         super().__init__(**kwargs)
> ```

**Comment by teddy171** [comment]
```python
import uvicorn
from fastapi import FastAPI, Response
from baize.asgi.responses import FileResponse


class ChunkFileResponse(Response):
    def __init__(self, *args, **kwargs) -> None:
        if len(args) == 1:
            kwargs = args[0]
            [kwargs.pop(k) for k in ['status_code', 'cookies', 'stat_result']]
        super().__init__(**kwargs)


app = FastAPI()


@app.get("/")
def file():
    return ChunkFileResponse(filepath="./demo.md")


if __name__ == '__main__':
    uvicorn.run('main:app', port=5555, reload=True)
```
Could you tell me what's wrong with the code? I still cannot get the file. It still shows json.

**Comment by abersheeran** [comment]
It seems to be caused by not specifying a `response_class`.

**Comment by teddy171** [comment]
Do you mean this?
```python
from fastapi import FastAPI, Response
from fastapi.staticfiles import StaticFiles
# from fastapi.responses import FileResponse
import uvicorn
# from starlette.responses import FileResponse
from baize.asgi.responses import FileResponse


class ChunkFileResponse(Response):
    def render(self, filepath):
        response = FileResponse(filepath)
        self.media_type = response.content_type
        return response


app = FastAPI()
app.mount("/static", StaticFiles(directory="static"), name="static")


@app.get("/", response_class=ChunkFileResponse)
def file():
    return "./demo.md"


if __name__ == '__main__':
    uvicorn.run('main:app', port=5555, reload=True)
```
It seem doesn't work. Fastapi raise following error.
```
Traceback (most recent call last):
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/fastapi/routing.py", line 251, in app
    response = actual_response_class(response_data, **response_args)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/starlette/responses.py", line 50, in __init__
    self.init_headers(headers)
  File "/Users/teddy/miniconda3/lib/python3.8/site-packages/starlette/responses.py", line 81, in init_headers
    content_length = str(len(body))
TypeError: object of type 'FileResponse' has no len()
```
